// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCisC6j9BkHY1hQKujVZluKd4P8kSsVtsQ',
    appId: '1:496064426539:web:d739b50607a0813027706e',
    messagingSenderId: '496064426539',
    projectId: 'mytodo-47c66',
    authDomain: 'mytodo-47c66.firebaseapp.com',
    storageBucket: 'mytodo-47c66.appspot.com',
    measurementId: 'G-R9HEE015JC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCixD9tsYHpffke9W-YTW14jKIPFZ0frJc',
    appId: '1:496064426539:android:ccb7d453e057fae727706e',
    messagingSenderId: '496064426539',
    projectId: 'mytodo-47c66',
    storageBucket: 'mytodo-47c66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV9YQ6THqM0c-lBTAbwxxKGzaPjTLXME0',
    appId: '1:496064426539:ios:0e8a6bf0723bd3f027706e',
    messagingSenderId: '496064426539',
    projectId: 'mytodo-47c66',
    storageBucket: 'mytodo-47c66.appspot.com',
    iosBundleId: 'com.todoapp.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV9YQ6THqM0c-lBTAbwxxKGzaPjTLXME0',
    appId: '1:496064426539:ios:edc9fd7c6fc4a77627706e',
    messagingSenderId: '496064426539',
    projectId: 'mytodo-47c66',
    storageBucket: 'mytodo-47c66.appspot.com',
    iosBundleId: 'com.todoapp.todo.RunnerTests',
  );
}
